// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    asset_loan
    (
        init => init
        upgrade => upgrade
        addToWhitelist => add_to_whitelist
        removeFromWhitelist => remove_from_whitelist
        isWhitelisted => is_whitelisted
        registerAsset => register_asset
        changeAssetStatus => change_asset_status
        registerLoan => register_loan
        returnAsset => return_asset
        getMyAssets => get_my_assets
        getAsset => asset
        getOwnerAssets => owner_assets
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
