// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    cf_ampliacio
    (
        init => init
        upgrade => upgrade
        fund => fund
        claim => claim
        SetMaxTarget => set_max_target
        SetMaxFunds => set_max_funds
        SetLimitFunds => set_limit_funds
        status => status
        getCurrentFunds => get_current_funds
        getTarget => target
        getMaxTarget => maxtarget
        getDeadline => deadline
        getDeposit => deposit
        getMaxFund => maxfund
        getLimitFund => limitfund
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
